# Generated by Django 2.2.1 on 2019-05-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hstu_school', '0003_event_news_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
