# Generated by Django 2.2.1 on 2019-05-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hstu_school', '0004_auto_20190517_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice_time',
            field=models.TimeField(auto_now_add=True, verbose_name='Conversation Time'),
        ),
    ]
