# Generated by Django 2.2.1 on 2019-05-17 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hstu_school', '0005_auto_20190517_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='notice_date',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='notice_time',
        ),
    ]
