# Generated by Django 2.2.1 on 2019-05-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hstu_school', '0006_auto_20190517_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_details',
            field=models.CharField(max_length=2000),
        ),
    ]
