# Generated by Django 2.2.1 on 2019-05-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hstu_school', '0008_auto_20190517_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
    ]
