# Generated by Django 2.2.1 on 2019-05-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hstu_school', '0010_fblink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Twitterlink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitterlink_date', models.DateField(auto_now_add=True, verbose_name='Conversation Date')),
                ('twitterlink', models.CharField(max_length=2000)),
            ],
        ),
    ]
