# Generated by Django 2.2.1 on 2019-05-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hstu_school', '0012_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_date', models.DateField(auto_now_add=True, verbose_name='Conversation Date')),
                ('pic1', models.CharField(max_length=20)),
                ('pic2', models.CharField(max_length=20)),
                ('pic3', models.CharField(max_length=20)),
            ],
        ),
    ]
