# Generated by Django 2.2.1 on 2019-05-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hstu_school', '0013_carousel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_date', models.DateField(auto_now_add=True, verbose_name='Conversation Date')),
                ('home_pic', models.CharField(max_length=20)),
                ('home_text', models.CharField(max_length=4000)),
            ],
        ),
    ]
